export const seo = {
  title:
    "Caio Landgraf | Senior Staff+ Infrastructure Engineer, Anthropic",
  tabTitle: "Caio Landgraf",
  titleTemplate: "%s | Caio Landgraf",
  description:
    "Senior Staff+ Infrastructure Engineer on Cluster Infrastructure at Anthropic. Previously Senior Software Engineer (L5) at Google Cloud, specializing in Distributed Systems, Cloud Infrastructure, Go, Rust, and AI.",
  keywords: [
    "Software Engineer",
    "Staff Engineer",
    "Infrastructure Engineer",
    "Cluster Infrastructure",
    "Anthropic",
    "Claude",
    "AI",
    "Backend Engineer",
    "Cloud Engineer",
    "DevOps",
    "Tech Lead",
    "Software Architecture",
    "Google Cloud",
    "Laravel",
    "Ruby on Rails",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "TypeScript",
    "Distributed Systems",
    "Cloud",
    "Docker",
    "Kubernetes",
    "AWS",
    "Google Cloud Platform",
    "PostgreSQL",
    "MySQL",
    "SQL",
    "Artificial Intelligence",
    "Open Source",
    "Technical Writing",
  ],
  authors: [{ name: "Caio Landgraf", url: "https://caiolandgraf.dev" }],
  creator: "Caio Landgraf",
  publisher: "Caio Landgraf",
  locale: "en_US",
  twitter: {
    handle: "@eicajo",
    site: "@eicajo",
  },
  ogTechnologies: ["AI", "Claude", "AWS", "Go", "Rust"],
} as const;
