export const seo = {
  title: "Caio Landgraf | Senior Software Engineer (L5), Google Cloud",
  titleTemplate: "%s | Caio Landgraf",
  description:
    "Senior Software Engineer (L5) at Google Cloud specializing in Backend Engineering, Distributed Systems, Cloud Infrastructure, Laravel, Go and Artificial Intelligence.",
  keywords: [
    "Software Engineer",
    "Backend Engineer",
    "Cloud Engineer",
    "DevOps",
    "Tech Lead",
    "Software Architecture",
    "Google Cloud",
    "Laravel",
    "Ruby on Rails",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "TypeScript",
    "Distributed Systems",
    "Cloud",
    "Docker",
    "Kubernetes",
    "AWS",
    "Google Cloud Platform",
    "PostgreSQL",
    "MySQL",
    "SQL",
    "Artificial Intelligence",
    "Open Source",
    "Technical Writing",
  ],
  authors: [{ name: "Caio Landgraf", url: "https://caiolandgraf.dev" }],
  creator: "Caio Landgraf",
  publisher: "Caio Landgraf",
  locale: "en_US",
  twitter: {
    handle: "@eicajo",
    site: "@eicajo",
  },
  ogTechnologies: ["Go", "Laravel", "Cloud", "Distributed Systems", "AI"],
} as const;
